### ISSUE TITLE
Docker image 4yr old

### ISSUE THREAD

**Issue by coolapso** [damoun/twitch_exporter#40]
Hi @damoun , hope you are well. What's the status of this exporter? 
Docker image seems to be 4yr old even tho this repository seems to be "somewhat" active.  you planning on keeping maintaining it? could I provide you with some assistance?  or would it be better if I fork it and maintain it on my side?

**Comment by damoun** [comment]
Hi, thanks for the comment.

I'm still looking to update the dependencies as I have a few PRs from renovatebot.

Anyway, I would accept PR if you want to contribute.

**Comment by coolapso** [comment]
Alright thanks. will see what I can help with.

**Comment by damoun** [comment]
I updated the dependencies and rebuild the docker image.

**Comment by coolapso** [comment]
Cool thanks a lot! :)

**Comment by damoun** [comment]
I'm pretty sure we can have more metrics from the Twitch API but from a quick review of their doc, you can work on any of this issues:
- #45 
- #46 
- #47
