### ISSUE TITLE
docker image: Permission denied when executing twitch_exporter

### ISSUE THREAD

**Issue by coolapso** [damoun/twitch_exporter#60]
When container image build the execute permissions are not being preserved therefore the twitch exporter binary is not executable and throws permission denied error. 

Steps to reproduce: 

```
docker run -p 9184:9184 \
        damoun/twitch-exporter \
        --twitch.client-id * \
        --twitch.access-token * \
        --twitch.channel cool4pso

```

Steps to verify: 

```
☸ virt01 ❯docker run -ti --entrypoint /bin/sh damoun/twitch-exporter
/ # ls -la /bin/twitch_exporter
-rw-r--r--    1 root     root      16303651 Jul 17 07:50 /bin/twitch_exporter
/ #
```

OBS: I Have already a solution for this, but there are other issues I am looking into before pushing and submmiting prs.

**Comment by damoun** [comment]
It's a bug with the github action to upload the build artifact https://github.com/actions/upload-artifact/issues/38
